// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkF_dURo7NWUIZnQWFFoUfPk2VN_fDTkU',
    appId: '1:855392053267:web:de5cfad1fd369d8b0637e6',
    messagingSenderId: '855392053267',
    projectId: 'fordemo-f4121',
    authDomain: 'fordemo-f4121.firebaseapp.com',
    storageBucket: 'fordemo-f4121.appspot.com',
    measurementId: 'G-X6GXG2ZN01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeSMnSOmEbh2ap23zk0R7ddPNAbXv66C4',
    appId: '1:855392053267:android:c9f573ec43f2d18a0637e6',
    messagingSenderId: '855392053267',
    projectId: 'fordemo-f4121',
    storageBucket: 'fordemo-f4121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf8wJ16RJD5_9TRQTxpdjyr7BczcKSdtY',
    appId: '1:855392053267:ios:71436d0dcdc004f30637e6',
    messagingSenderId: '855392053267',
    projectId: 'fordemo-f4121',
    storageBucket: 'fordemo-f4121.appspot.com',
    iosClientId: '855392053267-he7l45kjamth1vn3mkme4jlmv4t5cfa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf8wJ16RJD5_9TRQTxpdjyr7BczcKSdtY',
    appId: '1:855392053267:ios:71436d0dcdc004f30637e6',
    messagingSenderId: '855392053267',
    projectId: 'fordemo-f4121',
    storageBucket: 'fordemo-f4121.appspot.com',
    iosClientId: '855392053267-he7l45kjamth1vn3mkme4jlmv4t5cfa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkF_dURo7NWUIZnQWFFoUfPk2VN_fDTkU',
    appId: '1:855392053267:web:5bfbcfd74914508a0637e6',
    messagingSenderId: '855392053267',
    projectId: 'fordemo-f4121',
    authDomain: 'fordemo-f4121.firebaseapp.com',
    storageBucket: 'fordemo-f4121.appspot.com',
    measurementId: 'G-78SHGBRKLY',
  );
}
